#!/bin/sh

# Daemon for syncing clipboard between host and guest VM &
# for providing display drivers to set proper resolution
if command -v spice-vdagent > /dev/null; then
  spice-vdagent &
fi
sleep 1 &&

# Set screen resolution
if xrandr | grep -q '1360x768'; then
  xrandr -s 1360x768 &
else
  xrandr -s 1366x768 &
fi
sleep 1 &&

# Enable policy kit
if command -v lxpolkit > /dev/null; then
  lxpolkit &
fi
sleep 1 &&

# Set default volume
if command -v pactl > /dev/null; then
  pactl set-sink-mute 0 0 &
  pactl set-sink-volume 0 90% &
fi

# Enable volume control in sys tray
if command -v mate-volume-control-status-icon > /dev/null; then
  mate-volume-control-status-icon &
fi
