[window]
decorations = "None"
padding = { x = 3, y = 0 }
startup_mode = "Maximized"

[font]
size = 11.0
normal.family = "NotoSansMNerdFont"
bold.family = "NotoSansMNerdFont"
italic.family = "NotoSansMNerdFont"
bold_italic.family = "NotoSansMNerdFont"
